################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
board \
component/uart \
custom \
device \
drivers \
freertos/freertos-kernel \
freertos/freertos-kernel/portable/GCC/ARM_CM4F \
freertos/freertos-kernel/portable/MemMang \
generated \
generated/guider_fonts \
lvgl/src/core \
lvgl/src/display \
lvgl/src/draw \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/sdl \
lvgl/src/draw/sw/blend \
lvgl/src/draw/sw \
lvgl/src/drivers/display/drm \
lvgl/src/drivers/display/fb \
lvgl/src/drivers/display/ili9341 \
lvgl/src/drivers/display/lcd \
lvgl/src/drivers/display/st7735 \
lvgl/src/drivers/display/st7789 \
lvgl/src/drivers/display/st7796 \
lvgl/src/drivers/evdev \
lvgl/src/drivers/glfw \
lvgl/src/drivers/libinput \
lvgl/src/drivers/nuttx \
lvgl/src/drivers/qnx \
lvgl/src/drivers/sdl \
lvgl/src/drivers/wayland \
lvgl/src/drivers/windows \
lvgl/src/drivers/x11 \
lvgl/src/font \
lvgl/src/indev \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/layouts \
lvgl/src/libs/barcode \
lvgl/src/libs/bin_decoder \
lvgl/src/libs/bmp \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif \
lvgl/src/libs/libjpeg_turbo \
lvgl/src/libs/libpng \
lvgl/src/libs/lodepng \
lvgl/src/libs/lz4 \
lvgl/src/libs/qrcode \
lvgl/src/libs/rle \
lvgl/src/libs/rlottie \
lvgl/src/libs/tiny_ttf \
lvgl/src/libs/tjpgd \
lvgl/src \
lvgl/src/misc/cache \
lvgl/src/misc \
lvgl/src/osal \
lvgl/src/others/file_explorer \
lvgl/src/others/fragment \
lvgl/src/others/gridnav \
lvgl/src/others/ime \
lvgl/src/others/imgfont \
lvgl/src/others/monkey \
lvgl/src/others/observer \
lvgl/src/others/snapshot \
lvgl/src/others/sysmon \
lvgl/src/others/vg_lite_tvg \
lvgl/src/stdlib/builtin \
lvgl/src/stdlib/clib \
lvgl/src/stdlib \
lvgl/src/stdlib/micropython \
lvgl/src/stdlib/rtthread \
lvgl/src/themes/default \
lvgl/src/themes \
lvgl/src/themes/mono \
lvgl/src/themes/simple \
lvgl/src/tick \
lvgl/src/widgets/animimage \
lvgl/src/widgets/arc \
lvgl/src/widgets/bar \
lvgl/src/widgets/button \
lvgl/src/widgets/buttonmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/carousel \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/image \
lvgl/src/widgets/imagebutton \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/lottie \
lvgl/src/widgets/menu \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/roller \
lvgl/src/widgets/scale \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \
source/APP \
source/BSW \
source/RTE \
source \
startup \
touchpanel \
utilities/debug_console_lite \
utilities \
utilities/str \
video \

